---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-canary
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: market-data
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: market-data
        tier: backend
        track: canary
    spec:
      containers:
      - name: market-data
        image: BUILD_TAG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 15
